---
title: "IE 0015 Information Systems Syllabus"
author: "Louis Luangkesorn"
date: "Spring 2016"
output: html_document
---

Coarse goals
============

To be able to work with data and use programming and database tools for processing, manipulating, analyzing, and presenting data. To develop and implement algorithms for processing data. To understand and critique data analysis presentations.

Major Topics
==================================

1.  Databases
2.  Data manipulation
3.  Exploratory data analysis
4.  Algorithms with data (missing values)


# Materials

## Software

1.  R -  http://cran.r-project.org  Follow the appropriate download link for your platform

2.  R Studio - An Integrated Development Environment (IDE). A basic environment (editor, console) comes with R, so this is optional, however, highly recommended as it will be much easier with this.

http://www.rstudio.com/products/RStudio/#Desktop - Click on 'Download R Studio Desktop'.  You will be given options for your platform.  After installing this watch the video to get familiarized with the platform.

3.  Packages.  Much of the functionality of R is embedded in packages.  These need to be installed prior to use. (Note: installation of packages is easy given access to the internet.  You will quickly learn to recognize when it is necessary to install a package. But to start, you should enter the following in the R console after you install R and R Studio

install.packages(c(  "ggplot2",  "knitr",  "plyr",  "reshape2",  "dplyr",  "rJava",  "XLConnect",  "RODBC",  "RSQLite",  "chron",  "lubridate",  "stringr",  "stringdist",  "editrules",  "Hmisc",  "rspa",  "deducorrect"))

4.  SQLite - Available on MS Windows, Mac OS X, and other platforms. Free download from https://www.sqlite.org/download.html.  Note that DB Browser includes SQLite embedded in it. As does the RSQLite library in R so you may not need to install SQLite yourself.

5.  DB Browser for SQLite http://sqlitebrowser.org/

To use SQLite, it is best to use a Graphical based browser. Here is one: (note: if you know how to use another database tool that links to SQL databases, you are welcome to use it).

Firefox browser users can also use the SQLite Manager addon.



##  Books

The following are resources we will use.  Data Manipulation with R will be the primary text because that presents information in a way different than all other sources. 

1.  Data Manipulation with R - Spector (textbook)
2.  Using SQLite by Jay Kreibich
  -  http://shop.oreilly.com/product/9780596521196.do (get electronically through Pitt Library)
3.  GGplot2 book by Hadley Wickham
  - Available electronically through Pitt Library
4.  Introduction to R. https://cran.r-project.org/doc/manuals/R-intro.pdf. Also available within R Studio.
5.  An introduction to data cleaning with R by Edwin de Jonge and Mark van der Loo http://cran.r-project.org/doc/contrib/de_Jonge+van_der_Loo-Introduction_to_data_cleaning_with_R.pdf.
6.  OpenIntro Statistics, https://www.openintro.org/stat/?stat_book=os. This will not be used heavily, but is a useful reference on how to use R for the topics you covered in your Introduction to Statistics course.

##  Articles

-  Each week, an article will be posted for discussion.  Each article will be an example of a data analysis and will be a focus of discussion to consider both strengths and weaknesses of the data analysis and presentation.
-  The article discussions are intended to help you prepare for the exams. Exams are focused on being able to specify a data problem (CoNVO) and interpret exploratory data analysis output.


## Datasets

-  National Survey of Family Growth
-  American Community Survey
-  Titanic survivors

#  Grading

1.  Weekly labs               15%
2.  Midterm                   25%
3.  Final                     30%
4.  Project (3 person teams)  20%
5.  Class participation       10%

# ABET Outcomes

a. an ability to apply knowledge of mathematics, science, and engineering;
b. an ability to design and conduct experiments, as well as to analyze and interpret data;
e. an ability to identify, formulate, and solve engineering problems;
g. an ability to communicate effectively;
k. an ability to use the techniques, skills, and modern engineering tools necessary for engineering practice.


Schedule
========

- Module 0: Introduction to Data and R (Jan 6)
- Module 1: Using SQLite (Jan 11)
- Module 2: Using SQL and basic SQL query functions (Jan 20)
- Module 3: Reading data into R. Based on Spector Ch 2 (Jan 25)
- Module 4: Data formats Spector Ch 4, 5 (Feb 1)
- Module 5: Data formats Spector Ch 6, 7 (Feb 8)
- PROJECT TOPIC FEBRUARY 10 
- Module 6: Summarizing data (plyr) (Feb 15)
- Module 7: Simple graphs with ggplot2 (qplot) (Feb 22)
- MIDTERM March 3 (No labs)
- Module 8: Complex graphs with ggplot2 (qplot) (Mar 14)
- PROJECT EXPLORATORY DATA ANALYSIS MARCH 16
- Module 9: Data manipulation with plyr (based on Spect Ch 8, 9) (Mar 21)
- Module 10: Pivot tables and aggregations with table and reshape (Mar 28)
- Module 11: Identifying and marking missing values - Development of algorithms - flow charts (April 4)
- Module 12: Missing values imputation (April 11)
- Module 13: Statistical analysis (linear regression and sampling/Simulation) (based on IPSUR) (April 18)
- PROJECT REPORT AND PRESENTATIONS APRIL 20, 21, 22
- FINAL Wednesday, April 27, 2:00 - 3:50