---
title: 'RegionEx Case: Exploratory Data Analysis'
author: "IE 0015 Information Systems"
date: "January 23, 2019"
output:
  pdf_document: default
  html_document: default
---

**Due Wednesday February 6, 2019**

1.  Using R, read in the data.  Note where you need to transform data and how you did this (e.g. declare it to be factor, ordered, normalize data, etc.). You may have to complete question 2 before you can completely answer this.
2.  Describe the fields in the data set. Note: you may group fields if it makes sense (i.e. many fields are very similar in nature).
    i. Name
    ii. Short, one sentence description
    iii. Description of potential values (include data type and units)
    iv. Quantitative summary of data.  e.g. mean, median, 25/75 quartiles, range
    vi. Is this an outcome or a potential predictor? (dependent or independent variable)
3.  CoNVO statement
4.  Create a pairs plot. Identify some independent variables seem to produce variation in the outcome variables.  If there are more than 10 variables in the data set you should select 10 variables to include in the pairs plot. Use one paragraph to justify your choice of variables to include.
5.  Explore at least five independent variables as identified in the pairs plot.  Apply each of the five basic plot types at least once.  You may find that you have to build on the basic plot type to make something meaningful.
