---
title: "Project  Description"
author: "Information Systems"
date: "Spring 2020"
output: word_document
---


1.  Identify a large, complex data set
  -  Large - Larger than you can take the time to look at the entire set in Excel.
  -  At least two related tables (you may need to get two data sources to do this)
  -  Evaluate data set according to 4 V's
      i. Volume (how many records)
      ii. Variety (how many variables, can you classify the variables)
      iii. Velocity (does time matter)
      iv. Veracity (is there an issue with accuracy of the data)
2.  Process it
  -  The data must need processing
  -  Missing values
  -  Data entry errors
  -  Collapsing categories
  -  4 V's issues
3.  Summarize it
  -  Data summaries
  -  Visual
4.  Tell a story
  -  **Co**ntext
  -  **N**eeds
  -  **V**ision
  -  **O**utcome
5.  Report - Note final report format is same as Case Study

  
Timeline
--------

1. Teams of 1-3. Identify a data set and a potential CoNVO and basic plots of data 
- Part 1 above due
February 20
2. Exploratory data analysis - March 18
  - Detailed Exploratory Data Analysis of data set (2 and 3)
  - Refine CoNVO
3. Final Report April 15, Presentations April 16, 17 in lab
  - Final report same format and guidelines as the case study final

