---
title: 'Project: Exploratory Data Analysis'
author: "IE 0015 Information Systems"
date: "March 18, 2020"
output:
  pdf_document: default
  html_document: default
---

1.  Using R, read in the data.  Note where you need to transform data and how you did this (e.g. declare it to be factor, ordered, normalize data, etc.). You may have to complete question 2 before you can completely answer this.
2.  Describe data sets
    i. Volume (how many records)
    ii. Variety (how many variables, can you classify the variables)
    iii. Velocity (does time matter)
    iv. Veracity (is there an issue with accuracy of the data)
3.  Describe the fields in the data set. Note: you may group fields if it makes sense (i.e. many fields are very similar in nature).
    i. Name
    ii. Short, one sentence description
    iii. Description of potential values (include data type and units)
    iv. Quantitative summary of data.  e.g. mean, median, 25/75 quartiles, range
    vi. Is this an outcome or a potential predictor? (dependent or independent variable)
4.  CoNVO statement
5.  Create a pairs plot using `GGally::ggpairs()`. Identify some independent variables seem to produce variation in the outcome variables.  If there are more than 10 variables in the data set you should select 10 variables to include in the pairs plot. Use one paragraph to justify your choice of variables to include.
6.  Explore at least five independent variables as identified in the pairs plot.  You may find that you have to build on the basic plot types to make something meaningful. At least one should be related to the Vision part of your CoNVO statement.
