---
title: "Final topics"
author: "IE 0015 Information Systems"
date: "April 12, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Programming

-  For all questions that are based on algorithms, you may represent your answer in one of the following ways
    -  Process map
    -  Enumerated (numbered) outline
    -  Pseudocode (R, do not worry about getting the syntax correct)

## CoNVO statements

- Given a setting, write a CoNVO statement (four paragraphs)

## Strings, Factors, Dates

- Be able to describe the process of taking data and convert it to dates

## Advanced Programming

-  Working with pipes
-  dplyr
    -  Filter, mutate
    -  Group by, summarize, join
-  Writing functions
-  Conditionals (if)
-  Loops
-  Vectorizing

## Transforms and modeling

-  Scaling
-  Implementing scaling

## Linear Regression

-  Representing multiple linear regression model
-  Plotting residuals and interpreting residual plots
-  Identifying variables to add to linear regression model
-  Regression model diagnostics summaries, plots, and interpretation

## Simulation

-  Use of Monte Carlo simulation
-  Use of bootstrap simulation
-  Simulation for hypothesis testing
-  Interpreting simulation results for hypothesis testing
-  Interpretting p-values in simulation results