---
title: "Thinking About Data"
author: "IE 0015"
date: "January 2019"
output:
  pdf_document:
    default
  slidy_presentation: default
  beamer_presentation: 
    colortheme: whale
    theme: AnnArbor
---


Thinking about data
========================================================


Thinking about data
===================

-  We will spend most of our time looking at how to work with data.
-  But what we need to do first is think about why.
-  Define the problem.

Data as storytelling
====================

-  Our goal is looking at data is insight.
-  The alternative to looking at data is _____.
-  To do better, we need to ask good questions and develop a story.
-  To tell a good story, we need to learn a structure to a story.



Scoping a data project
======================

-  **Co**ntext
-  **N**eeds
-  **V**ision
-  **O**utcome

Context
=======

Context
=======

- Context is the frame that is apart from the particular problem we are trying to solve.
- *The big picture*
- Who is interested in the results of this project?
- What are they generally trying to achieve?
- What overall work is this project contributing to?

Sources of contexts
=====================

- Long term goals
- Organization missions
- Decision points
- Personal curiosity

Example
=======

- A gym or fitness center is interested in the fitness of its clientele

Needs
======


Needs
======

-  Needs are challenges that are to be met through the data project.
-  Needs should be presented in terms of the organization.
-  The need is NOT build a model/chart/graph. The need is to solve a specific problem.

How can data fill needs
=======================

-  Create knowledge.
-  Understand some part of how the world works.
-  Better understanding leads to better decisions.
-  What will we do differently if we have the knowledge that data gives us?

Learning what the needs are
===========================

-  Talking to people.
-  Ask for stories about what the people involved care about, what they work on, what they are stuck on.
-  Ask questions to dig deeper into what needs to be understood, why, and by whom.


What makes a good need
======================

-  Relates directly to an action that depends on having good information.
-  Information will inform an action.
-  Information could be related to a bigger strategic question in meeting the organizations larger goals.
-  Without a good definition of need, the work is fluff.
-  A need is a problem, the need is never *we need a tool*.
-  How does a gym or a trainer program activity for clients to meet their individual goals?

Vision
======


Vision
======

-  Where are we going?
-  What might it look like to achieve our goal?

What does success look like?
============================

-  What are potential results of the data analysis?
-  What kind of argument will you make with the data?
-  What kind of decisions will result from seeing outcomes?

Talking about results
=========================

-  How will the data be used to support the decisions?
-  How should the data be presented to best support the use of the data?
-  Mockups of the output
  -  Example reports of outcomes
  -  Simplified graphs
  -  Sketches of displays or user interfaces to spark discussion of using a tool
-  How can fitness be defined and quantified? How can the performance of workouts be compared and improvement measured?

Thinking about arguments
=========================

-  The results of data analysis should be a decision.
-  The results need to advocate one choice over another.
-  Question:  What makes a convincing case of one choice over another?  Will the data analysis provide that case?

Aspects of an argument
======================

-  Who needs to be convinced? What is their background, their priorities?
-  Are they interested in subjective or objective measurements?
-  Do they need an experiment?

This defines how simple or complex the data analysis needs to be.

Outcome
=======


Outcome
=======

-  How will the data analysis be used?
-  How will it be integrated into the organization?
-  Who will own the integration?
-  Who will use it?
-  How will success be measured?

Who will have to use the results
===

-  Who will interpret or act on the work?
-  Who are they?
-  What are their requirements?

Who will handle keeping the work relevant?
==========================================

-  Will this need to be rerun at some point?
-  What needs to be adjusted between runs?

What do we hope will change after we finish the work?
========

-  What will change in the organization?
-  How do we verify the change?
-  What kind of results does a trainer hope to see?

Course datasets
===============


Titanic dataset
===============

-  Dataset includes all passengers on the Titanic.
-  Cruise liner that was advertised as unsinkable.
-  Crashed into iceberg and sank on first trans-Atlantic voyage.
-  High fatalities, in part because there were not enough lifeboats for the number of passengers and crew.
-  CoNVO - Who survived? What characteristics?

National Survey of Family Growth
=================================

- Conducted by the U.S. Centers for Disease Control
- Intended to gather “information on family life, marriage and divorce, pregnancy, infertility, use of contraception, and men’s and women’s health. The
survey results are used to plan health services and health education programs, and to do statistical studies of families, fertility, and health*
- We will focus on the Female pregnancy file.
- What questions can we ask?
- E.g. "are first babies born late"

CrossFit Open 2017-2018
======================

-  Performance data of a mass participation worldwide fitness competition
-  Countries, affiliates (gym) 
-  How do individuals compare across a range of fitness workouts?
-  **Look up what these events are on the internet before lab**

American Community Survey
=========================

- Sample of approximately 1/40 households per year.
- Public Use Microdata Area (PUMA) - Pittsburgh north of the Monongahela River.
- Survey includes demographics, employment, educational, housing, health, questions.
- Because we have the raw survey results, we can look at cross correlations.
