---
title: 'Homework 1: Data manipulation verbs with R and dplyr'
author: "IE 0015"
date: "January 30, 2020"
output:
  html_document: default
  pdf_document: default
---

For the homework assignments, code and narrative should be written using R Markdown. Where process maps are needed you may write them in as pseudocode, draw them and add them to a Word Document You should render (knit) the R Markdown as a Word document, print the output, and staple with the process maps for the complete submission.

The first part of this homework assignment you will repeat labs 1 and 2, but you will do them in R using the dplyr/magrittr packages. Then you will generate the five basic plots.

```{r, warning=FALSE}
library(tidyr)
library(dplyr)
library(magrittr)
library(ggplot2)
library(readxl)
library(readr)
```



1. Load the affiliate and the two CrossFit Open files based on the following rule:

-  Use the first letter of your last name. 
-  If you are in a team of two, use the last name of the person whose first name comes first alphabetically.

Last (family) name:  A-L: Men,  M-Z: Women


1. [15] Affiliates would like to compare where they are to other nearby affiliates.  The CrossFit Open organizes athletes into regions.  Do the following using `dplyr`, 
Identify all athletes who participated in the CrossFit Open in both 2019 and 2020.  List the top 10 affiliates based on the number of athletes who competed from that affiliate in 2019 for the region that represents your place of birth. 

a. [5] Make list of repeat athletes
b. [5] Group athletes and count by affiliate based on 2020 affiliation.
c. [5] Identify top 10 affiliates and calculate the number of repeat athletes who were there in 2020, and the average and spread of the improvement in rank.

Notes: 
    -  You should use the 2020 data to identify athletes by affiliate. 
    -  Regions are identified in the athlete table. You should find an affiliate in your state/province to figure out what region you are in.  
    -  You should make the list of repeat athletes first, then group by and summarize by affiliate, then filter by region.

2. [10] For the top 10 affiliates in the region, calculate and show the number of athletes, average improvement in rank, and standard deviation of improvement in rank of those who participated in both the 2019 and 2020 Open.  

3.  [15] For your region, take the top 10 affiliates and create a boxplot of the improvement in the athletes for those affiliates.

Note: that your plot needs labels for the x and y axis and a title that identifies the information presented and the region the plot is for.

Note: search on the internet for "ggplot rotate axis labels" to see how to rotate the x-axis labels.

4. [10]  For one of the top 5 affiliates in the region, create a plot that shows the improvement in rank of each athlete who participated in both the 2019 and 2020 Open.  Assume that your client is the owner of that affiliate.  Explain to the owner how to interpret the plot and the implication.  Note that the plot needs meaningful axis titles and a main title. 
