---
title: "Reading data into databases"
author: "IE0015 Lab 1"
date: "January 10/11, 2020"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

Note: This lab should be done as a Word file so you can cut and paste MS Access output to answer questions as needed.  When a query is required, you may use the MS Access Query Wizard to design the query, then use the SQL View to display the resulting SQL that will go into your answer. 

1. [1] Download the Affiliate data from Courseweb (My Documents -> Data Sets) and look at it using a text editor (Notepad or the R Studio editor). 

What character separates fields in this file?  What character identifies text that should be kept in the same data field? (Note: only some records need to especially identify text, what distinguishes them) What would happen if you did not identify text that should be kept together?

2. [1]  Using the MS Access, import the Affiliate list data using default settings. How many rows and columns are in the resulting table?  

3. [1]  Using default settings, for several records the data fields are in the wrong column.  What causes this error?  Re-import the Affiliate list and set the options so this is done correctly.  Set the Affiliate ID to be the primary key.


Download the CrossFit 2019/2020 Open data from Kaggle (link is in Course Documents -> Datasets )
4. [1]  Look at the 2019 Opens Athletes dataset in a text editor. Import the dataset into MS Access.  Set the UserID to be the primary key. Check that the field types make sense. Allow for duplicates.  What happened to the column names?

5. [2]  Load in the remainder of the data files (2019 Opens scores, 2020 Opens athleets, 2020 Opens scores).  Check for import errors.  What import errors were there?  Find the errors in the original CSV file (import in Excel).  Lookup the workout on google (search for CrossFit Open (year)) and explain the error in terms of the workout.


For problems 5 and 6, you will do the lab based on your last name and your birth month.

Last (family) name:  A-L: Women,  M-Z: Men
Birth month:  Jan - June:  2019,  July-December: 2020

5. [1]  The final result of the CrossFit Open is the sum of the ranks.  Modify the table design that calculates the sum of the ranks of athletes in your dataset, then sort the athletes by rank.  Confirm that this gives the same results as the field "Overall rank"

Write how you modified the table design (include a copy and paste of the equation) and copy and paste in a table that shows the correct result.


6. [3]  Create a query that does the following:

    i. For each affiliate (gym), identify the number of athletes who entered the CrossFit Open that year.
    ii.  What is the minimum (best) sum of ranks for that affiliate.
    iii.  What is the maximum (worst) sum of ranks for that affiliate.
    
Select SQL View and copy and paste the results of the SQL view.  Also submit a table (copy and paste into word) with the top 10 affiliates, sorted by the number of athletes entered.
