---
title: 'Lab 12: Regression'
author: "IE 0015 Information Systems Engineering"
date: "April 2015"
output: pdf_document
---

```{r loadlibraries,  warning=FALSE}
options(digits = 3, scipen=4)
library(RSQLite, quietly = TRUE)
library(ggplot2)
library(VIM, quietly = TRUE)
titanic <- read.csv("../data/titanictrain.csv",
                    header=TRUE, sep=",")
# From Lab on working with characters and regular expressions
getTitle <- function(data) {
  title.dot.start <- regexpr("\\,[A-Z ]*\\.", data$Name, TRUE)
  title.comma.end <- title.dot.start+ attr(title.dot.start, "match.length")-1
  data$Title <- substr(data$Name, title.dot.start+2, title.comma.end-1)
  return (data$Title)
}  
titanic$Title <- getTitle(titanic)
#unique(titanic$Title)  
```

# 1.  kNN imputation (3pts).

Identify the records that are missing age data.  Include the information from the title as part of information on each passenger.
  a. Use kNN imputation to fill in these values based on 7 nearest neighbors.
  b. Display a few of the records that previously were  missing ages.  How does the records that were imputed using kNN compare to the methods you used in last week's lab? Explain your answer.

# 2. Regression (7 pts)

You think that the age is dependent on the following

  i.  Sex
  ii.  Pclass
  iii.  Title
  iv.  Fare
(Note: so few people have SibSp or Parch that you are going to ignore these)

  a.  Develop a multiple linear regression model for the age based on these characteristics for use in missing value imputation.
  b.  Display the summary and the analysis of variance tables for this model. Comment on each of the four predictors that are in your model and make corrections as needed.
  c.  Display diagnostics plots. Discuss the three assumptions of regression models.
  