---
title: 'Lab 2: Database forms and reports'
author: "IE 0015 Information Systems Engineering"
date: "01/16-17/2020"
output:
  word_document: default
  html_document: default
  pdf_document: default
---


This lab uses the CrossFit Open data you used in last week's lab. You should start with the database from last week and the division that you used last week  The goal for this lab is creation of a report for the owner of an affiliate (gym).

Last (family) name:  A-L: Women,  M-Z: Men
Birth month:  Jan - June:  2019,  July-December: 2020

1. [8] Pick one affiliate from the list of top 10 affiliates from last year.  Create a query that identifies all athletes from that affiliate (as specified by the athlete table) and their scores for each event in that year's Open.  The result should include:

    1. Affiliate Name
    2. Competitor Name
    3. Competitor Division
    4. Competitor overall rank
    5. Event number (ordinal)
    6. Event breakdown (description)
    7. Competitor event rank
    8. Score (as displayed)

Note that in the event of multiple scores for an event, use the best (minimum rank).  Also, you need to confirm that the division and scaled fields are matched (competitors sometimes enter in more than one division.  We want Men/Women (no age group) and not scaled (is_scaled=0).

2. [4] Create a form for that affiliate that displays the same data as the query in question 1.  Make it so that you are able to see the entire workout description.

Note:  You do not need to create a subform, so data for each may appear completely on its own form

3. [8] Create a report that for the given affiliate, that provides the scores by each competitor.  The report should list the competitor information once, then the information for each of the workouts.
