---
title: 'Lab 3: SQL Joins'
author: "Louis Luangkesorn"
date: "01/21/2015"
output: pdf_document
---

NOTE:  To compare a number that is stored as a string to be a number, use CAST.

```
SELECT p.SERIALNO, p.AGEP, h.FPARC, h.FES
FROM ss12ppa AS p JOIN ss12hpa as h
ON p.SERIALNO=h.SERIALNO
WHERE cast(p.AGEP as REAL) BETWEEN 0 AND 18
AND h.FPARC IN ("1", "2", "3")
AND h.FES IN ("5", "6", "7", "8")
```


1. [1] Determine the fields which identify the number of people in the household, and the type of household ownership (Group Quarter (i.e. dorms, prisons, military barracks), Rental, Own).

ANSWERS

- TEN identifies type of ownership
- NP identifies people in household

2.  [2] Determine the percentage of people of people who live in Group Quarters, Rent, Own (include mortgage), or are not currently paying for hoursing.  Include query(ies), the resulting table, and the percentages of people.

```
SELECT TEN, count(SERIALNO), sum(NP) 
FROM ss12hpa
GROUP BY TEN
```

Tenure | Number of households | People in households | Percent total
-----|-----|----|---
"GQ" |   "458"	| "387" | 0.203
"Own(Mortgage)" |	"219"	| "507" | 0.266
"Own (no mortgage)"	| "155"	| "272" | 0.142
"Rent"	| "407"	| "707" | 0.371
"Occupied (no rent)"	| "16"	| "36" | 0.019

1909 people


3.  [3] New York City recently instituted universal Pre-Kindergarden for four year-olds.  What is the fraction of 4/5 year olds in Pre-K in Pittsburgh (North)? 
  a.  What field identifies age of child?
  b.  What field identifies if the child is in school?
  c.  Generate a query that identifies the school status of 4 and 5 year olds. Do not include children in Kindergarden should not be counted (because they have finished eligibility for Pre-K)
  d.  What is the fraction of 4 and 5 year olds in pre-school/pre-K?
  
ANSWERS

  a.  p.AGEP where p is ss12ppa
  b.  p.SCH or p.SCHG for which grade
  c.  

```
SELECT count(p.SERIALNO), p.AGEP, p.SCHG
FROM ss12ppa AS p 
WHERE cast(p.AGEP as INTEGER) BETWEEN 4 AND 5
AND cast(P.SCHG as INTEGER) < 2
GROUP BY p.SCHG
```
  
  0.636 (or 63%)

4.  [4] What fraction of pre-school age children (under 6) live in households with a grandparent?
  a.  What field in what table identifies households with children?
  b.  What field in what table identifies if grandparents are living with grandchildren in the household?
  c.  What query determines how many children under 6 are living in a household?
  d.  Determine what fraction of children of pre-school age (under 6) live in households with a grandparent.
  
  
  
ANSWERS

  a.  HUPAC in the household table (=1, 3 if children under 6 present)
  b.  HUGCL in the household table (=1 if grandparents with grandchildren)
  c.  Note that the count has to come from the personal survey table, as the household table only indicates that children are present, not how many. (you could get number of people in the household, but you would not know which ones were children)  
  
```
SELECT count(p.SERIALNO), h.HUGCL
FROM ss12ppa AS p 
JOIN ss12hpa as h
ON p.SERIALNO=h.SERIALNO
WHERE cast(p.AGEP as INTEGER) BETWEEN 0 AND 5
GROUP BY h.HUGCL
```

d.  

Number children under 6 | Grandparents present
---|---
"85" |  "0"
"6"	| "1"

0.066 (or 6.6%)

