---
title: 'Lab 5: Data formats'
author: "IE 0015 Information Systems"
date: "Spring 2016"
output: pdf_document
---

For all questions, submit the code you used to determine the answer (if any) as well as the answer.

Read in the `beavers` data that is included in R.  The data was taken in 1990 in Wisconsin. For both the `beaver1` and `beaver2` dataset, the `day` field is days since the beginning of 1990.

1.  For each dataset, calculate the date for each data record. What dates are represented in each data file? (ideally, this should be within the data frame, but we will not take points off if this is a vector that corresponds to the dataset). (Hint:  add days to January 1, 1990)

2.  Look at the time stamps. What makes this hard to work with. Write out an algorithm (in pseudocode or plain english) that converts this time into a time stamp

3.  In the Titanic data, list the people with the following characteristics
  -  Embarked in Queenstown
  -  Female
  -  Known to be under the age of 19 (i.e. 18 and under)
  
4.  In the Titanic data, plot a histogram of ages in 5 year increments separated by Sex (gender) include a meaningful plot title, and x and y axis labels. Note: Look at the help file for qplot. You want to use the titanic data set, the geometry is "histogram", to separate histograms by Sex, you use "facets = Sex ~ ."  To set the size of a histogram width you use "binwidth=".