---
title: 'Lab 6: Subsetting'
author: "IE 0015: Information Systems"
date: "02/18/2016"
output: pdf_document
---

```{r loadtitanic }
titanic <- read.csv("../data/titanictrain.csv")
```
1.  (4 pts) In the time of the Titanic, Victorian England was very class conscious. 

  i. Load the Titanic passenger data and specify that the Survived and Pclass variables are factors.
  ii. Create three subsets based on the passenger class. For each, have the Passenger ID number, Passenger class, gender, and age and outcome (survived). You will need to specify both the individuals (rows) and the variables to include (columns) (Hint: How do you determine what passenger class a given passenger is staying in? (first class, second class, third class)).  
  iii. Print out the summary of the first subset (Class 1 passengers).  Identify which variable's summary does not make sense and state what should you do about it?

2.  (3 pts)  Family size

The total number of family members is given by two variables, `SibSp` (Siblings and spouse, i.e. same generation) and `Parch` (Parents and children, i.e. the older or younger generation).

  i.  Create a new variable called family that adds these together as part of the original Titanic data frame.
  ii.  Plot a histogram for the number of family members that includes all three classes on the same graph. Use both color and pattern to differentiate between the classes (remember to include a chart title, x-axis and y-axis labels) (note: you should use the geometry "histogram". To color in the histogram bar, you can set the 'fill' parameter to be equal to the passenger class. This will create a stacked histogram, to make bars side by side you will need to use the `ggplot` command instead of `qplot` (not necessary for this lab))
  iii.  Does this answer the question "How large were embarked families on the Titanic?" (Hint: No) Why not?
  
3.  (3 pts) Age distribution

Plot the age distribution for each class of passenger. Use a faceted histogram plot with a `binwidth=5` (i.e. one plot for each class, on top of each other) (remember that the form of the `facets` parameter to qplot is `facets = . ~ variablename` or `facets = variablename ~ .`. Note the location of '.' in each case.)

