---
title: 'Lab 8: Character Strings'
author: "IE 0015 Information Systems"
date: "February 27-28, 2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r loadtitanic, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(magrittr)
library(stringr)
titanic <- read.csv("../data/titanictrain.csv")
```
1.  (3 pts) The Titanic accident was in a time when people were identified by their titles. In the Titanic data, How do you identify the title (Mr., Mrs., Miss. etc) of a person? Draw a flow chart for this procedure.

Hint: open the Titanic csv file in R Studio and try to tell someone else exactly how to identify the title without pointing to the file. Then you know how to write the flow chart.

2.  (5 pts) Read in the titanic data and extract the title of each person. (i.e. implement (1)) Make a list of unique titles.  

- Note 1: Look in lecture Rmd file
- Note 2: How do you find the first letter? how do you know the title is complete? 
- Note 3:  To use the regular expression tool in R Studio, open the datafile (csv), then Find, then click the Regex box.  Remember that the regex tool does not require escape backslashes, but your code will.
- Note 4:  in a regular expression, you need to escape the punctuation with a backslash, and you need to escape the backslash with another backslash (i.e. two backslashes before a punctuation mark.)
- Note 5:  to apply a function to a each element in a dataframe) use `sapply`, e.g. `sapply(dataframe$column, FUN=sqrt)` or `rowwise() %>% mutate(. . .)`
  

3.  (2 pts) How many passengers have each title? (Note: requires code)
